location: "./repos"
indepth: true
counttotal: false
langscount: 5
style:
  theme: "./themes/tokyonight.yml"
  type: "compact"
  count: "lines"
  bytesbase: 1024
  showtotal: true
token: "repo scoped access token"
excludeforks: true
parallel: 8
users:
  - "ppebb"
orgs:
  - "Retro-Rewind-Team"
repositories:
  - "ppebb/libclang-lua"
  - "ppebb/cosmo-stub-generator"
authors:
  - "ppeb"
  - "ppebb"
  - "ppeb@ppeb.me"
filters:
  - "reaganism"
  - "terraprisma"
ignore:
  vendor: true
  dotfiles: true
  binary: true
  configuration: true
  image: true
  test: true
  generated: true
  langs:
    - "CSV"
    - "Roff Manpage"
